baseURL = "https://master.d1pxjj95w4qhah.amplifyapp.com/"
languageCode = "en-us"
title = "Jonathan Whitaker"
theme = "hyde"

pygmentsUseClasses=true
pygmentsCodeFences=true

disqusShortname = "jon-whit"

summaryLength = 72

# Site Settings
[params]
  themeColor = "theme-base-0d"
  author = "Jonathan Whitaker"
  description = "Write a nice site description."

# Social Accounts
[params.social]
  github = "jon-whit"
  stackoverflow = "3342427/jonathan"
  email = "jon.b.whitaker@gmail.com"

# Main Menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog Section"
    url = "/blog/"
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About Page"
    url = "/about/"
